name: General Test and Deploy
on: 
  push:
jobs:
  setup-virtualenv:
    runs-on: ubuntu-latest
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Fetch Env Vars from Doppler
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
  linter:
    needs: setup-virtualenv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Linters
        run: |
          pip install isort black
          isort --check-only --diff .
          black --check --diff .

  tests:
    needs: setup-virtualenv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          mkdir -p /data
          sudo chown -R $USER:$USER /data
          sudo chmod 777 /data
          cd nhhc
          coverage run manage.py test web --settings=nhhc.test_settings --verbosity=2 --keepdb   --failfast  --force-color
